캐글 Human Activity Recognition with Smartphones 데이터
XGBoost를 사용
인간의 행동 패턴을 학습
입력값이 들어갔을 때 그 패턴 안에 있다면 output으로 0
임계값 이상으로 벗어나면 1을 내보내는
프로그램

In [3]:
import pandas as pd
import xgboost as xgb
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np

전처리

In [4]:
# 데이터 로드 및 전처리
from google.colab import files

train_data = pd.read_csv('/content/data/train.csv')
test_data = pd.read_csv('/content/data/test.csv')

# train_data = pd.read_csv('train.csv')
# test_data = pd.read_csv('test.csv')

X_train = train_data.iloc[:, :-2].values
X_test = test_data.iloc[:, :-2].values
y_train = train_data.iloc[:, -1].values
y_test = test_data.iloc[:, -1].values

# 클래스 인코딩
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# 데이터 스케일링
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

XGBoost 모델을 훈련

In [ ]:
# # XGBoost 모델 훈련
# model = xgb.XGBClassifier()
# model.fit(X_train, y_train)

# 하이퍼파라미터 그리드 설정
param_grid = {
    'learning_rate': [0.05, 0.1, 0.15],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9],
    'n_estimators': [100, 200, 300]
}

# GridSearchCV로 하이퍼파라미터 튜닝
xgb_model = xgb.XGBClassifier()
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)

# 최적의 하이퍼파라미터 출력
print("Best parameters: ", grid_search.best_params_)



/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [ ]:
# 예측
y_pred = model.predict(X_test)

# # 최적의 모델로 예측 및 평가
# best_model = grid_search.best_estimator_
# y_pred = best_model.predict(X_test)
# class_report = classification_report(y_test, y_pred)
# print(class_report)

In [ ]:
# # 결과 출력
# threshold = 0.05  # 일정 오차 범위 설정
# diff = np.abs(y_test - y_pred)
# if np.max(diff) <= threshold:
#     print("입력한 데이터는 학습된 패턴 내에 있습니다.")
# else:
#     print("입력한 데이터는 학습된 패턴을 벗어납니다.")

y_pred = model.predict(X_test)
y_pred_decoded = label_encoder.inverse_transform(y_pred)
print(y_pred_decoded)

['STANDING' 'STANDING' 'STANDING' ... 'WALKING_UPSTAIRS'
 'WALKING_UPSTAIRS' 'WALKING_UPSTAIRS']


In [ ]:
import pickle

# 모델 저장
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

# # 저장된 모델 불러오기
# with open("model.pkl", "rb") as f:
#     loaded_model = pickle.load(f)

In [ ]:
for i in range(len(y_pred)):
    print(f"Test sample {i+1}: Predicted={label_encoder.inverse_transform([y_pred[i]])[0]}, Actual={y_test[i]}")

Test sample 1: Predicted=STANDING, Actual=2
Test sample 2: Predicted=STANDING, Actual=2
Test sample 3: Predicted=STANDING, Actual=2
Test sample 4: Predicted=STANDING, Actual=2
Test sample 5: Predicted=STANDING, Actual=2
Test sample 6: Predicted=STANDING, Actual=2
Test sample 7: Predicted=STANDING, Actual=2
Test sample 8: Predicted=STANDING, Actual=2
Test sample 9: Predicted=STANDING, Actual=2
Test sample 10: Predicted=STANDING, Actual=2
Test sample 11: Predicted=STANDING, Actual=2
Test sample 12: Predicted=STANDING, Actual=2
Test sample 13: Predicted=STANDING, Actual=2
Test sample 14: Predicted=STANDING, Actual=2
Test sample 15: Predicted=STANDING, Actual=2
Test sample 16: Predicted=STANDING, Actual=2
Test sample 17: Predicted=STANDING, Actual=2
Test sample 18: Predicted=STANDING, Actual=2
Test sample 19: Predicted=STANDING, Actual=2
Test sample 20: Predicted=STANDING, Actual=2
Test sample 21: Predicted=STANDING, Actual=2
Test sample 22: Predicted=STANDING, Actual=2
Test sample 23: Pre

In [ ]:
# 행동패턴 + 임계값 0.05 범위 벗어나면 1 아니면 0
for i in range(len(y_pred)):
    diff = np.abs(y_test[i] - y_pred[i])
    if diff <= 0.05:
        threshold = 0
    else:
        threshold = 1
    print(f"Test sample {i+1}: Predicted={label_encoder.inverse_transform([y_pred[i]])[0]}, Actual={y_test[i]}, Threshold={threshold}")

Test sample 1: Predicted=STANDING, Actual=2, Threshold=0
Test sample 2: Predicted=STANDING, Actual=2, Threshold=0
Test sample 3: Predicted=STANDING, Actual=2, Threshold=0
Test sample 4: Predicted=STANDING, Actual=2, Threshold=0
Test sample 5: Predicted=STANDING, Actual=2, Threshold=0
Test sample 6: Predicted=STANDING, Actual=2, Threshold=0
Test sample 7: Predicted=STANDING, Actual=2, Threshold=0
Test sample 8: Predicted=STANDING, Actual=2, Threshold=0
Test sample 9: Predicted=STANDING, Actual=2, Threshold=0
Test sample 10: Predicted=STANDING, Actual=2, Threshold=0
Test sample 11: Predicted=STANDING, Actual=2, Threshold=0
Test sample 12: Predicted=STANDING, Actual=2, Threshold=0
Test sample 13: Predicted=STANDING, Actual=2, Threshold=0
Test sample 14: Predicted=STANDING, Actual=2, Threshold=0
Test sample 15: Predicted=STANDING, Actual=2, Threshold=0
Test sample 16: Predicted=STANDING, Actual=2, Threshold=0
Test sample 17: Predicted=STANDING, Actual=2, Threshold=0
Test sample 18: Predict

In [ ]:
# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# classification report
class_report = classification_report(y_test, y_pred)
print(class_report)

[[537   0   0   0   0   0]
 [  0 420  68   0   0   3]
 [  0  28 504   0   0   0]
 [  0   0   0 487   5   4]
 [  0   0   0   9 384  27]
 [  0   0   0  31   5 435]]
Accuracy: 0.94
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       537
           1       0.94      0.86      0.89       491
           2       0.88      0.95      0.91       532
           3       0.92      0.98      0.95       496
           4       0.97      0.91      0.94       420
           5       0.93      0.92      0.93       471

    accuracy                           0.94      2947
   macro avg       0.94      0.94      0.94      2947
weighted avg       0.94      0.94      0.94      2947



In [ ]:
# ## 수동 입력
# # 예측 함수
# def predict(input_data):
#     input_data = np.array(input_data).reshape(1, -1)
#     input_data = scaler.transform(input_data)
#     y_pred = model.predict(input_data)
#     y_pred_decoded = label_encoder.inverse_transform(y_pred)
#     return y_pred_decoded[0]
#
# # 사용자 입력 받아서 예측 결과 출력
# while True:
#     input_data = input("Input data (sepal_length, sepal_width, petal_length, petal_width): ")
#     input_data = input_data.strip().split(',')
#     if len(input_data) != 4:
#         print("Invalid input. Please enter 4 values separated by comma.")
#         continue
#     try:
#         input_data = [float(x) for x in input_data]
#     except ValueError:
#         print("Invalid input. Please enter numeric values.")
#         continue
#     result = predict(input_data)
#     print(f"Predicted class: {result}")

In [ ]:
# # 입력 데이터 준비
# # 실시간으로 들어오는 데이터가 변수 5개로 이루어진 Numpy 배열이라 가정하면...
# new_data = np.array([1.5, 2.3, -0.1, 0.8, 1.2])
#
# # 데이터 스케일링
# new_data_scaled = scaler.transform(new_data.reshape(1, -1))
#
# # 모델 예측
# new_pred = model.predict(new_data_scaled)
#
# # 예측 결과 디코딩
# new_pred_decoded = label_encoder.inverse_transform(new_pred)
# print(new_pred_decoded)
#
# # 이렇게 가는게 맞나....?

ValueError: X has 5 features, but StandardScaler is expecting 561 features as input.

버전
xgboost 1.7.5
sklearn 1.2.2
Python 3.10.10
PyCharm 2023.1.1