In [2]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
rand = tf.random.uniform([1],0,1) # (shape, 최솟값, 최댓값)
print(rand) #  shape=(1,) 튜플형태 원소가 하나이지만 튜플임을 알리기 위해 , 사용

tf.Tensor([0.16656494], shape=(1,), dtype=float32)


In [ ]:
rand = tf.random.uniform([4],0,1)
print(rand)

tf.Tensor([0.02607763 0.38211334 0.49802947 0.9950414 ], shape=(4,), dtype=float32)


In [ ]:
rand = tf.random.normal([4],0,1) # 종모양을 그리는 정규분포의 난수를 구하려면 uniform대신 normal사용.
print(rand)
# 여기서 1이상도 나오고 마이너스 값도 나오는 이유? normal에서는 (shape, 정규 분포의 평균(mean), 정규분포의 표준편차)

tf.Tensor([-0.36753684  0.5371224   1.073336    0.37725145], shape=(4,), dtype=float32)


활성화 함수
- sigmoid : 오류 역전파시 시그모이드가 함수값을 점점 적어지게하는 문제 은닉층을 다수 사용하면 점점 덜 쓰임.
- ReLU 정류된 선형 함수 : 양수를 그대로 반환해서 왜곡이 적어짐. 

In [3]:
import math
def sigmoid(x):
  return 1 / (1+math.exp(-x))

In [ ]:
x = 1
y = 0 # 기대출력
w = tf.random.normal([1],0,1)
output = sigmoid(x * w) # 실제 출력
print(output) # 실제 출력인 0.5003103644886976와 기대출력인 0의 차인 0-0.5003103644886976=-0.5003103644886976이 error
# 뉴런의 학습은 이 에러가 0에 가까워 지게 해서 출력으로 기댓값에 가까운 값을 얻는 것. 여기서 뉴런이란 결국 w 값.

0.5003103644886976


- 실제 출력인 0.5003103644886976와 기대출력인 0의 차인 0-0.5003103644886976=-0.5003103644886976이 error
- 뉴런의 학습은 이 에러가 0에 가까워 지게 해서 출력으로 기댓값에 가까운 값을 얻는 것. 여기서 뉴런이란 결국 w 값. 이 값을 변화시켜야함. -> 경사하강법
- 경사하강법 : w = w + (입력 * 학습률(α) * 에러) 
(학습률(α)은 w를 업데이트 하는 정도. 너무 크면 범위를 벗어날 우려가 있고 너무 작으면 학습속도가 너무 느려짐.)
w = w + (x * α * error)

In [ ]:
# 1 -> 0
for i in range(1000): # range 범위에 해당하는 리스트 자동으로 생성
  output = sigmoid(x * w)
  error = y - output # 에러 = 기대출력 - 실제출력
  w = w + (x * 0.1 * error)

  if i % 100 == 99:
    print(i, error, output)

99 -0.052317247185330505 0.052317247185330505
199 -0.03483169587994336 0.03483169587994336
299 -0.02602571258070615 0.02602571258070615
399 -0.020745724131793136 0.020745724131793136
499 -0.017234561890340526 0.017234561890340526
599 -0.014733762999709339 0.014733762999709339
699 -0.01286334812246372 0.01286334812246372
799 -0.011412269032075427 0.011412269032075427
899 -0.010254088341387179 0.010254088341387179
999 -0.00930844722656234 0.00930844722656234


In [4]:
# 0 -> 1
x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
  output = sigmoid(x * w) # x가 0, w에 더해지는 값이 없음 -> bias(편향)을 뉴런에 넣어줌.
  error = y - output
  w = w + (x * 0.1 * error)

  if i % 100 == 99:
    print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [8]:
# + bias
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
  output = sigmoid(x * w + 1 * b)
  error = y - output
  w = w + (x * 0.1 * error)
  b = b + (1 * 0.1 * error)

  if i % 100 == 99:
    print(i, error, output)


99 0.08423476875522085 0.9157652312447792
199 0.04699809642271058 0.9530019035772894
299 0.03235455697438183 0.9676454430256182
399 0.02460656940952055 0.9753934305904794
499 0.01982962895780216 0.9801703710421978
599 0.01659551236737855 0.9834044876326214
699 0.014263089666910367 0.9857369103330896
799 0.012502497674481972 0.987497502325518
899 0.011126959384108792 0.9888730406158912
999 0.010022906084027006 0.989977093915973
